### ISSUE TITLE
 HomeScreen Design

### ISSUE THREAD

**Issue by Tris0205** [Tris0205/CNPMNC#1]
- [x] Hiển thị các note theo dạng lưới (mặc định).

- [x] Thiết kế Menu (Sửa, Sắp xếp, hiển thị).

- [x] Thiết kế Navigation Drawer (Thùng rác, Khoá, Yêu thích, Thiết lập).

- [x] Thiết kế nút thêm ghi chú (floating button).

- [x] Thiết kế nút tìm kiếm.

**Comment by nambibobib** [comment]
Đã thiết kế xong trên Figma

**Comment by nambibobib** [comment]
Đã update thêm
