### ISSUE TITLE
 NoteScreen Design

### ISSUE THREAD

**Issue by Tris0205** [Tris0205/CNPMNC#2]
- [x] Ghi tiêu đề, nội dung.

- [x] Thiết kế menu định dạng văn bản (Bottom Navigation): Canh lề, font chữ (Đậm, nghiêng, gạch dưới), màu chữ, kích thước chữ, Backward, Foward.

- [x] Thiết kế Menu (Khoá ghi chú, xoá ghi chú, thêm ghi chú vào yêu thích).

- [x] Autosave khi thoát ra màn hình HomeScreen.

**Comment by nambibobib** [comment]
Đã thiết kế xong trên Figma
